language: java
sudo: false
jdk:
  - openjdk17
branches:
  only:
    - main
    - develop
    - feature/ala-upgrade
cache:
  directories:
    - $HOME/.m2
jobs:
  include:
    - stage: Build and Run All Tests
      name: "Build and Tests"
      script:
        - mvn verify